server:
  port: 8671

spring:
  application:
    name: msc-eureka-server

eureka:
  instance:
    hostname: eureka01
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 单机设置
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群设置
      defaultZone: http://eureka02:8672/eureka/