server:
  port: 9010

spring:
  application:
    name:  BUSINESS-USER

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8671/eureka/,http://127.0.0.1:8672/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
